export const phrases = [
	'Ek is lief vir jou',
	'Ek het jou lief',
	'Te dua',
	'Afekrishalehou',
	'Ana Behibek',
	'Kezi chat ge sirem',
	'Yes kez sirum em',
	'Yes kez shat em siroom',
	'Mi stimabo',
	'Az tha hijthmekem',
	'Men seni severam',
	'Maite zaitut',
	'I mog di narrisch gern',
	'Ami tomAy bhAlobAshi',
	'Lakh tirikh',
	'Ham tahara se pyar karila',
	'Namumutan ta ka',
	'Nahigugma ko nimo',
	'Volim te',
	'Eu te amo',
	'Obicham te',
	'Bon sro lanh oon',
	'Ngo oi ney',
	"T'estim",
	"T'estime",
	"T'estimo",
	'Gi Gugma Kita',
	'Hey-Ben-nahh',
	'Hu Guiya Hao',
	'Main Tere bina main ji nahi pauga',
	'Wo ie ni',
	'Wo ai ni',
	'Volim te',
	'Miluji te',
	'Jeg elsker dig',
	'Aharen Kalaa Dhekeh Loabivey',
	'Ik hou van jou',
	'I love you',
	'Mi amas vin',
	'Ma armastan sind',
	'Tora dust midaram',
	'Ik zie je graag',
	'Mina rakastan sinua',
	"Je t'aime",
	'Ik bin fereale op dy',
	'Ta gra agam ort',
	'Ámote',
	'Me shen mikvarkhar',
	'Ich liebe dich',
	'I mog Di ganz arg',
	"S'agapo",
	'Ina sonki',
	"Aloha wau ia 'oe",
	'Main tumse pyar karta hun',
	'Gwa ai di',
	"Nu' umi unangwa'ta",
	'Kuv Hlub Koj',
	"Szeretlek te'ged",
	'Ég elska þig',
	'Moi tumak val pau',
	'Tane Prem Karoo Choo',
	'Nanu nimmege preti maditi idini',
	'Hom ahaan sei pyaar karey chhi',
	'Aina nangbu nunshi',
	'Mu tumaku bhala paye',
	'Main tenu pyar karda haan',
	'Aue tosa pyaar kar ya to',
	'Naan Unnai Khadalikkeren',
	'Nenu ninnu premisthunnaanu',
	'Mala tujhashi prem aahe',
	'Saya cinta padamu',
	'Saya cintakan awak',
	'Saya cintamu',
	'Omasido khou',
	'Kulo tresno panjenengan',
	"Taim i' ngra leat",
	'Ti amo',
	'Ichaddaw ko imo',
	'Kimi o ai shiteru',
	'Aku terno kowe',
	'Ya Eh Na Arr Gyi Law',
	'Meh chi chain maai',
	'Men seny jaksy kuremyn',
	'Nakupenda',
	'Hanv tukka preeti karta',
	'Tangsinul sarang ha yo',
	'Ez te hezdikhem',
	'Washem Grakani',
	'Men seni syuem',
	'Nga naw hta ha ja',
	'Khoi huk chau',
	'Chanrackkun',
	'Te amo',
	'Es Tevi milu',
	'Nalingi yo',
	'Að myliu tave',
	'Nkwagala',
	'Aheri',
	'Te sakam',
	'Me molas, tronca',
	'Saya cinta awak',
	'Inħobbok',
	'Inchepoyeneimi',
	'Konoronhkwa',
	'Te iubesc',
	'Bi chamd khairtai',
	'Nga nint ko chit dae',
	"Ayor anosh'ni",
	'Ngiyakuthanda',
	'Jeg elsker deg',
	'Za Tasara Meena Kawam',
	'Tora dost daram',
	'Mahal Kita',
	'Kocham cię',
	'Eu amo-te',
	'Main tenu pyar karda haan',
	'Te iubesc',
	'Я люблю тебя',
	'Volim te',
	'Ndinokuda',
	'Mama Oyata Aadarei',
	'Techihhila',
	'Lubim ta',
	'Ljubim te',
	'Waan kujeclahay',
	'Te quiero',
	'Naku penda',
	'Jag älskar dig',
	'Mahal kita',
	'Gwa ai lee',
	'Naan Unnai Khadalikkeren',
	'Phom Rak Khun',
	'Nga Chola Gagai Yo',
	'Seni seviyorum',
	'Я тебе кохаю',
	'Mea tum se pyaar karta hu',
	'Ik zie je graag or ik hou van je',
	"Rwy'n caru ti",
	'Mi te voeuri ben',
	'Ndiyakuthanda',
	'Ikh hob dikh lib',
	'Mo ni ife re',
	'Ezhele hezdege',
	"Tom ho' ichema"
]
